--Tabela de Produtos
CREATE TABLE Produtos(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL UNIQUE,
	preco DECIMAL(10,2) NOT NULL,
	estoque INTEGER NOT NULL DEFAULT 0,
	data_dadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--Tabela de Pedidos
CREATE TABLE Pedidos(
	id SERIAL PRIMARY KEY,
	cliente_nome VARCHAR(100) NOT NULL,
	data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	total DECIMAL(10,2) DEFAULT 0
);

